[*]
desktop_bg=#000000
desktop_shadow=#000000
desktop_fg=#9A9996
desktop_font=Nunito Sans Light 12
wallpaper=/home/ndpi-client/ndpi-monitor-client/Assets/no-signal-overlay.svg
wallpaper_mode=fit
show_documents=0
show_trash=0
show_mounts=0
folder=/home/ndpi-client/Desktop